#!/bin/bash

./spherical_trades -b -u 6  > spherical_bitrades_4
./spherical_trades -b -u 8  > spherical_bitrades_6
./spherical_trades -b -u 9  > spherical_bitrades_7
./spherical_trades -b -u 10 > spherical_bitrades_8
./spherical_trades -b -u 11 > spherical_bitrades_9
./spherical_trades -b -u 12 > spherical_bitrades_10
./spherical_trades -b -u 13 > spherical_bitrades_11
./spherical_trades -b -u 14 > spherical_bitrades_12
