#!/bin/bash

./spherical_trades_binary -b -u 6  > binary_spherical_bitrades_4
./spherical_trades_binary -b -u 8  > binary_spherical_bitrades_6
./spherical_trades_binary -b -u 9  > binary_spherical_bitrades_7
./spherical_trades_binary -b -u 10 > binary_spherical_bitrades_8
./spherical_trades_binary -b -u 11 > binary_spherical_bitrades_9
./spherical_trades_binary -b -u 12 > binary_spherical_bitrades_10
./spherical_trades_binary -b -u 13 > binary_spherical_bitrades_11
./spherical_trades_binary -b -u 14 > binary_spherical_bitrades_12
