#!/bin/bash

echo "Compiling spherical bitrade generator..."
echo

cd spherical_bitrade_generator
./compile_binary

echo
echo "Generating spherical bitrades up to size 12..."
echo

./run_binary

echo
echo "Compiling C++ triangle dissection enumerator code..."
echo

cd ../dissections-cpp
./compile

echo
echo "Enumerating dissections up to some fixed size (12?)..."
echo

./run

echo
echo "Counting canonical signatures..."
echo

./count-signatures &> signature_counts_test_run.txt

echo
echo "Checking counts..."
echo

cmp signature_counts_test_run.txt signature_counts_known_correct.txt

RETVAL=$?
[ $RETVAL -eq 0 ] && echo "Success - all counts match:" && echo && cat signature_counts_test_run.txt 
[ $RETVAL -ne 0 ] && echo "Fail! Compare signature_counts_test_run.txt and signature_counts_known_correct.txt"




