#!/bin/bash

cat ../spherical_bitrade_generator/binary_spherical_bitrades_4 | ./td_binary > separated-signatures-4

# There are no trades of size 5.

for i in {6..14}
do
    echo $i
    cat ../spherical_bitrade_generator/binary_spherical_bitrades_$i | ./td_binary > separated-signatures-$i
done

